# Generated by Django 2.2 on 2019-05-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_history',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=50, verbose_name='value')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
