# Generated by Django 2.2 on 2019-05-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(default='', max_length=50, verbose_name='value')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
